-- Migration: create expenses table
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    team_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    description VARCHAR(5000) NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    expense_date DATE NOT NULL,
    paid_by_user_id BIGINT UNSIGNED NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NULL,
    project_id BIGINT UNSIGNED NULL,
    split_type ENUM('equal','exact','percentage','shares') NOT NULL DEFAULT 'equal',
    status ENUM('draft','submitted','approved','rejected','reimbursed') NOT NULL DEFAULT 'draft',
    approval_notes VARCHAR(2000) NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    reimbursed_by BIGINT UNSIGNED NULL,
    reimbursed_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED NULL,
    deletion_reason VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    KEY idx_expenses_team_date (team_id, expense_date),
    KEY idx_expenses_team_status (team_id, status),
    KEY idx_expenses_team_payer (team_id, paid_by_user_id),
    KEY idx_expenses_team_project (team_id, project_id),
    KEY idx_expenses_team_category (team_id, category_id),
    CONSTRAINT fk_expenses_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    CONSTRAINT fk_expenses_payer FOREIGN KEY (paid_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_expenses_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_expenses_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_expenses_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_expenses_rejecter FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
